"""Advisory declaration scaffold for evidence gaps that need a human.

Several evidence gaps can only be closed by a reviewed human declaration —
what a tool's effect is, what authority it runs with, which object is the root
agent. The decision engine already generates the exact manifest snippet each
one wants (``EvidenceGapAction.declaration_template``), but until now those
snippets were only reachable inside ``report.json`` at
``release_decision.evidence_coverage.evidence_gaps[].next_action.declaration_template``,
which made a one-time, three-line task look like schema archaeology.

This module assembles them into one reviewable YAML snippet next to
``report.json``, the same way ``suggested-inventory.json`` is written for
low-confidence sources. It asserts nothing: every value the human owns stays
``<REVIEW_REQUIRED>``, and a file full of sentinels satisfies no gap. Deciding
remains entirely the decision engine's job.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import yaml

from agents_shipgate.ci.release_decision import REVIEW_REQUIRED_SENTINEL
from agents_shipgate.schemas.report import EvidenceGap, ReadinessReport


def scaffold_for_report(report: ReadinessReport) -> str | None:
    """Render the scaffold for a report, or ``None`` when nothing is owed."""

    decision = report.release_decision
    if decision is None or decision.evidence_coverage is None:
        return None
    return build_declaration_scaffold(decision.evidence_coverage.evidence_gaps)


def build_declaration_scaffold(gaps: Sequence[EvidenceGap]) -> str | None:
    """Render the paste-ready scaffold, or ``None`` when nothing is owed.

    Deterministic: gaps are consumed in the order the decision engine emitted
    them, and templates aimed at the same manifest target are merged once.
    """

    # Group by the manifest path plus the subject the template is about, then
    # merge. Two gaps on one tool (an undeclared effect and an undeclared
    # authority) want ONE ``action_surface.actions`` row, so emitting them as
    # two blocks would hand the human something invalid to paste.
    sections: list[dict[str, Any]] = []
    by_target: dict[tuple[str, str, str], dict[str, Any]] = {}
    for gap in gaps:
        action = gap.next_action
        template = getattr(action, "declaration_template", None)
        if not isinstance(template, dict) or not template:
            continue
        path = str(getattr(action, "path", "") or "shipgate.yaml")
        # Key on the rendered selector, not the display name: two canonical
        # tools can share a name, and folding those into one row would produce
        # a declaration that resolves neither of them.
        target = (
            path,
            str(gap.subject or ""),
            str(template.get("tool_id") or template.get("tool") or ""),
        )
        existing = by_target.get(target)
        if existing is None:
            entry: dict[str, Any] = {
                "path": path,
                "kinds": [str(gap.kind)],
                "template": dict(template),
            }
            by_target[target] = entry
            sections.append(entry)
            continue
        if str(gap.kind) not in existing["kinds"]:
            existing["kinds"].append(str(gap.kind))
        for key, value in template.items():
            existing["template"].setdefault(key, value)

    if not sections:
        return None

    lines = [
        "# Declaration scaffold generated by agents-shipgate.",
        "#",
        "# Each block below is what one evidence gap needs before this repository",
        f"# can reach a `passed` verdict. Replace every {REVIEW_REQUIRED_SENTINEL}",
        "# with a reviewed value, merge the block into shipgate.yaml at the path",
        "# named above it, then re-run verification.",
        "#",
        "# These are human declarations on purpose. Agents Shipgate will not guess",
        "# a tool's effect, its authority, or which object is the root agent, and",
        f"# a block still containing {REVIEW_REQUIRED_SENTINEL} closes nothing.",
        "#",
        "# Some fields are co-required: `authority.mode: none` takes no",
        "# `auth_type` and no `scopes`, while `scoped` requires both. Delete the",
        "# lines your answer does not take.",
    ]
    for entry in sections:
        # Each block is its own YAML document. Concatenated mappings would
        # repeat top-level keys (two `tool:` roots), which is not a file a
        # reader or a parser can make sense of.
        lines.append("")
        lines.append("---")
        lines.append(f"# closes: {', '.join(entry['kinds'])}")
        lines.append(f"# merge into: {entry['path']}")
        # sort_keys=False keeps the engine's own field order, which reads the
        # way the manifest is written (subject first, then the declaration).
        rendered = yaml.safe_dump(
            entry["template"], sort_keys=False, default_flow_style=False
        )
        lines.append(rendered.rstrip("\n"))
    return "\n".join(lines) + "\n"


__all__ = ["build_declaration_scaffold", "scaffold_for_report"]
