"""Auto-mode YAML assembly for ``shipgate init``.

Builds a *valid* ``shipgate.yaml`` from a :class:`DetectResult`. The output
is run through ``AgentsShipgateManifest.model_validate(...)`` before write
to enforce schema correctness (see plan §2 validation gate).

Each detected Python-AST framework gets one ``tool_sources`` entry per
candidate file. Anthropic is artifact-only and gets a ``anthropic:``
config block populated from glob discovery. OpenAPI/MCP suggested sources
are emitted as ``tool_sources`` entries.

The ``--minimal`` mode in ``main.py`` bypasses this module and uses
``artifacts.render_manifest_template`` directly to preserve
backwards-compatibility with the v0.5.x template. Both renderers derive
``tool_sources[].id`` from the same helper (``source_ids.py``) — the one
place where v0.16 changed the legacy output, because a basename-only id
made both of them render manifests the schema rejects (#307).
"""

from __future__ import annotations

import re
from pathlib import Path

from agents_shipgate.cli.discovery.artifacts import (
    OPENAI_API_ANCHOR_KEYS,
    discover_anthropic_artifacts,
    discover_n8n_artifacts,
    discover_openai_api_artifacts,
)
from agents_shipgate.cli.discovery.manifest_scaffold import (
    RenderedManifest,
    ToolSurfaceOrigin,
    scaffold_tool_sources_block,
)
from agents_shipgate.cli.discovery.signals import select_agent_name
from agents_shipgate.cli.discovery.source_ids import assign_source_ids
from agents_shipgate.core.control_packs import (
    DEFAULT_CONTROL_PACK_ID,
    manifest_control_pack_block,
)
from agents_shipgate.schemas.detect import DetectResult

# Frameworks that register one tool_sources entry per candidate file.
PYTHON_AST_FRAMEWORKS = {"langchain", "crewai", "google_adk", "openai_agents_sdk"}


def render_auto_manifest(
    workspace: Path,
    detect_result: DetectResult,
    *,
    control_pack: str = DEFAULT_CONTROL_PACK_ID,
) -> RenderedManifest:
    """Build a schema-valid ``shipgate.yaml`` for a detected workspace.

    Falls back to a CHANGE_ME-heavy scaffold when no framework was
    detected (mirroring today's static-init behavior; ``--minimal`` is
    the dedicated path for the pre-v0.6 template).

    Returns the text together with :attr:`RenderedManifest.tool_surface_origin`, because
    whether the tool surface was *read* or *scaffolded* is decided here — by
    the four block builders below — and a caller that re-derived it would be
    answering the same question a second time, from less. ``init`` needs the
    answer to say plainly what it wrote (#441).
    """
    workspace = workspace.resolve()
    project_name = _project_name(workspace, detect_result)
    agent_name = _agent_name(detect_result)

    lines: list[str] = [
        "# yaml-language-server: $schema=https://raw.githubusercontent.com/ThreeMoonsLab/agents-shipgate/main/docs/manifest-v0.1.json",
        "# Agents Shipgate manifest (auto-generated by `shipgate init`).",
        "# Review fields below; CHANGE_ME placeholders need human input.",
        'version: "0.1"',
        "",
        "project:",
        f"  name: {project_name}",
        "",
        "agent:",
        f"  name: {agent_name}",
    ]

    # The manifest schema requires non-empty declared_purpose unless a
    # prompt-bearing framework block is present. Auto-init can't infer
    # purpose, so we always seed one CHANGE_ME entry — agents replace it
    # in the same turn that fills in agent.name.
    if agent_name == "CHANGE_ME":
        lines.append("  # No strong agent-name signal found; replace CHANGE_ME with the agent's role.")
    else:
        lines.append("  # Replace CHANGE_ME with a one-line description of what this agent should do.")
    lines.append("  declared_purpose:")
    lines.append("    - CHANGE_ME")
    lines.append("  prohibited_actions: []")
    lines.append("")

    lines.append("environment:")
    lines.append("  target: local")
    lines.append("")

    tool_source_lines, used_python_frameworks = _tool_sources_block(workspace, detect_result)
    anthropic_lines = _anthropic_block(workspace, detect_result)
    openai_lines = _openai_api_block(workspace, detect_result)
    n8n_lines = _n8n_block(workspace, detect_result)

    tool_surface_origin: ToolSurfaceOrigin = "detected"
    if not tool_source_lines and not anthropic_lines and not openai_lines and not n8n_lines:
        # Schema requires ≥ 1 of tool_sources / openai_api / anthropic /
        # google_adk / langchain / crewai. Nothing was read, so the manifest
        # carries a scaffold — and says so, in the YAML and in the caller's
        # return value alike.
        tool_surface_origin = "scaffold"
        tool_source_lines = scaffold_tool_sources_block()

    # Excluded-source hints are comments, appended only after the fallback
    # decision above so they can never stand in for a real tool_sources
    # block in the schema-requirement check.
    tool_source_lines.extend(_excluded_sources_hint(detect_result.excluded_sources))

    if tool_source_lines:
        lines.extend(tool_source_lines)
        lines.append("")

    if anthropic_lines:
        lines.extend(anthropic_lines)
        lines.append("")

    if openai_lines:
        lines.extend(openai_lines)
        lines.append("")

    if n8n_lines:
        lines.extend(n8n_lines)
        lines.append("")

    lines.extend(_policies_block(control_pack))
    lines.append("")
    lines.extend(_permissions_block())
    lines.append("")
    lines.extend(_ci_and_output_block())
    lines.append("")
    return RenderedManifest(text="\n".join(lines), tool_surface_origin=tool_surface_origin)


def _project_name(workspace: Path, detect_result: DetectResult) -> str:
    for candidate in detect_result.project_name_candidates:
        if candidate.source == "pyproject":
            return _safe_yaml_scalar(candidate.value)
    return _safe_yaml_scalar(workspace.name)


def _agent_name(detect_result: DetectResult) -> str:
    selected = select_agent_name(detect_result.agent_name_candidates)
    if selected is None:
        return "CHANGE_ME"
    return _safe_yaml_scalar(selected.value)


def _safe_yaml_scalar(value: str) -> str:
    """Quote scalars containing YAML-significant characters."""
    if value == "":
        return '""'
    if re.match(r"^[A-Za-z0-9_][A-Za-z0-9_.\-]*$", value):
        return value
    return '"{}"'.format(value.replace('"', '\\"'))


def _tool_sources_block(
    workspace: Path, detect_result: DetectResult
) -> tuple[list[str], set[str]]:
    """Build the ``tool_sources:`` block. Returns the lines plus the set
    of Python-AST framework types that contributed entries (used to
    suppress duplicate config blocks downstream)."""
    lines: list[str] = []
    used: set[str] = set()
    entries: list[tuple[str, str, str | None]] = []  # (type, path, mode)
    seen_paths: set[str] = set()

    for framework in detect_result.frameworks:
        if framework.type not in PYTHON_AST_FRAMEWORKS:
            continue
        for candidate in framework.candidate_files:
            if candidate in seen_paths:
                continue
            seen_paths.add(candidate)
            entries.append((framework.type, candidate, None))
            used.add(framework.type)

    for source in detect_result.suggested_sources:
        path = source["path"]
        if path in seen_paths:
            continue
        seen_paths.add(path)
        entries.append((source["type"], path, None))

    for candidate in detect_result.codex_plugin_candidates:
        path = candidate.path
        if path in seen_paths:
            continue
        seen_paths.add(path)
        entries.append(("codex_plugin", path, candidate.mode))

    if not entries:
        return [], used

    # Ids are assigned for the block as a whole: paths are deduplicated
    # above, but two distinct paths must not end up sharing an id — the
    # manifest schema rejects the whole render when they do (#307).
    entry_ids = assign_source_ids([(entry[0], entry[1]) for entry in entries])

    lines.append("tool_sources:")
    for (framework_type, path, mode), entry_id in zip(entries, entry_ids, strict=True):
        lines.append(f"  - id: {entry_id}")
        lines.append(f"    type: {framework_type}")
        lines.append(f"    path: {path}")
        if mode is not None:
            lines.append(f"    mode: {mode}")
    return lines, used


def _excluded_sources_hint(excluded: list[dict[str, str]]) -> list[str]:
    """Comment-only hint for glob-matched files the input adapters reject.

    These were dropped from ``tool_sources`` because writing them would
    guarantee a ``scan`` input-parse failure (exit 3) on the very next step
    of the cold-start flow. The hint keeps them reviewable without making
    the manifest unscannable.
    """
    if not excluded:
        return []
    lines = [
        "# Detected but excluded — `scan` cannot parse these as tool sources:",
    ]
    for entry in excluded:
        lines.append(f"#   {entry['path']} ({entry['type']}): {entry['reason']}")
    lines.append(
        "# If one of these is a real tools export, fix its format and add it "
        "to tool_sources."
    )
    return lines


def _anthropic_block(workspace: Path, detect_result: DetectResult) -> list[str]:
    """Emit anthropic config from discovered artifacts.

    Decoupled from framework detection (per v0.6 reviewer feedback): an
    artifact-only Anthropic project (tools/anthropic-tools.json,
    policies/anthropic-policy.yaml) shouldn't drop to a CHANGE_ME stub
    just because no Python import was found. Anthropic is artifact-based
    by design.
    """
    artifacts = discover_anthropic_artifacts(workspace)
    # Only emit if at least one Anthropic-specific artifact is present.
    # Bare prompts/ alone is ambiguous (OpenAI projects also have prompts);
    # tools/anthropic-tools.json and policies/anthropic-policy.yaml are
    # the load-bearing markers.
    anthropic_specific_keys = ("tools", "policy_rules")
    if not any(artifacts.get(key) for key in anthropic_specific_keys):
        return []
    lines = ["anthropic:"]
    if artifacts["prompt_files"]:
        lines.append("  prompt_files:")
        for path in artifacts["prompt_files"]:
            lines.append(f"    - {path}")
    if artifacts["tools"]:
        lines.append("  tools:")
        for path in artifacts["tools"]:
            lines.append(f"    - path: {path}")
    if artifacts["policy_rules"]:
        lines.append("  policy_rules:")
        for path in artifacts["policy_rules"]:
            lines.append(f"    - path: {path}")
    return lines


def _openai_api_block(workspace: Path, detect_result: DetectResult) -> list[str]:
    """Emit openai_api config from discovered artifacts.

    Decoupled from framework detection (per v0.6 reviewer feedback): a
    workspace with prompts/ and tools/openai-tools.json is a valid
    artifact-only OpenAI API project even without ``openai-config.json``
    or any ``from agents import`` Python source. Auto-init must not
    produce a CHANGE_ME stub for those repos.
    """
    artifacts = discover_openai_api_artifacts(workspace)
    # Only emit if at least one OpenAI-specific artifact is present.
    # Bare prompts/ alone could belong to an Anthropic-only project; the
    # OpenAI-specific artifact patterns (tools/openai-tools.json,
    # openai-config.json, tests/*openai*cases*.json,
    # policies/*openai*.yaml, policies/*api*.yaml) anchor the block.
    if not any(artifacts.get(key) for key in OPENAI_API_ANCHOR_KEYS):
        return []
    lines = ["openai_api:"]
    if artifacts["prompt_files"]:
        lines.append("  prompt_files:")
        for path in artifacts["prompt_files"]:
            lines.append(f"    - {path}")
    if artifacts["tools"]:
        lines.append("  tools:")
        for path in artifacts["tools"]:
            lines.append(f"    - path: {path}")
    if artifacts["response_formats"]:
        lines.append("  response_formats:")
        for path in artifacts["response_formats"]:
            lines.append(f"    - path: {path}")
            lines.append("      downstream_critical_fields: []")
    if artifacts["model_config"]:
        lines.append("  model_config:")
        lines.append(f"    path: {artifacts['model_config'][0]}")
    if artifacts["test_cases"]:
        lines.append("  test_cases:")
        for path in artifacts["test_cases"]:
            lines.append(f"    - path: {path}")
    if artifacts["trace_samples"]:
        lines.append("  trace_samples:")
        for path in artifacts["trace_samples"]:
            lines.append(f"    - path: {path}")
    if artifacts["policy_rules"]:
        lines.append("  policy_rules:")
        for path in artifacts["policy_rules"]:
            lines.append(f"    - path: {path}")
    return lines


def _n8n_block(workspace: Path, detect_result: DetectResult) -> list[str]:
    artifacts = discover_n8n_artifacts(workspace)
    if not artifacts["workflows"] and not any(
        framework.type == "n8n" for framework in detect_result.frameworks
    ):
        return []
    lines = ["n8n:"]
    _append_artifact_paths(
        lines,
        "workflows",
        artifacts["workflows"],
        placeholder="CHANGE_ME.json",
    )
    _append_artifact_paths(lines, "credential_stubs", artifacts["credential_stubs"])
    _append_artifact_paths(lines, "variable_stubs", artifacts["variable_stubs"])
    _append_artifact_paths(
        lines,
        "data_table_schemas",
        artifacts["data_table_schemas"],
    )
    lines.append("  execution_samples: []")
    _append_artifact_paths(lines, "eval_sets", artifacts["eval_sets"])
    lines.append("  tool_inventories: []")
    return lines


def _append_artifact_paths(
    lines: list[str],
    key: str,
    paths: list[str],
    *,
    placeholder: str | None = None,
) -> None:
    if not paths and placeholder is None:
        lines.append(f"  {key}: []")
        return
    lines.append(f"  {key}:")
    for path in paths or [placeholder]:
        lines.append(f"    - path: {path}")


def _policies_block(control_pack: str) -> list[str]:
    return [
        "# ADD policies for write/high-risk tools (approval, confirmation, idempotency).",
        "policies:",
        *manifest_control_pack_block(control_pack),
        "  require_approval_for_tools: []",
        "  require_confirmation_for_tools: []",
        "  require_idempotency_for_tools: []",
    ]


def _permissions_block() -> list[str]:
    return [
        "permissions:",
        "  scopes: []",
    ]


def _ci_and_output_block() -> list[str]:
    return [
        "ci:",
        "  mode: advisory",
        "",
        "output:",
        "  directory: agents-shipgate-reports",
        "  formats:",
        "    - markdown",
        "    - json",
    ]
