#!/usr/bin/env python3
"""Regenerate every committed dependency lock with one command.

Each lock in ``constraints/`` carries a hand-written header explaining what
installs it and why it is locked, followed by a generated closure. Recompiling
by hand meant running the right ``uv pip compile`` incantation per file and then
re-attaching the header the tool had just overwritten — a procedure that is
easy to skip, and a lock nobody dares regenerate stops matching the
declarations it is supposed to pin.

This runs the compile for every target in one pass and restores each file's
prose header, so updating a dependency is:

    python -m pip install -e ".[dev]"      # or however you already work
    # edit pyproject.toml / constraints/*.in
    python scripts/update_locks.py
    python scripts/verify_dependency_lock.py

The targets are the same table ``scripts/verify_dependency_lock.py`` gates, so a
lock cannot be generated by one and ignored by the other.

Resolution depends on the resolver, so the uv version is reported and compared
against the pinned publication toolchain: a lock compiled by a different uv can
differ from the one CI reviewed even when nothing in the declarations changed.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess  # noqa: S404 - invokes uv, an explicit developer tool
import sys
from pathlib import Path

if __package__:
    from scripts._release_support import ReleaseError
    from scripts.verify_dependency_lock import (
        DECLARATION_SENTINEL,
        LOCK_TARGETS,
        REPO_ROOT,
        LockTarget,
        declared_requirements,
        render_declarations,
    )
else:  # ``python scripts/update_locks.py``
    from _release_support import ReleaseError
    from verify_dependency_lock import (
        DECLARATION_SENTINEL,
        LOCK_TARGETS,
        REPO_ROOT,
        LockTarget,
        declared_requirements,
        render_declarations,
    )

# Matches the floor in `requires-python`; a universal resolution covers every
# later interpreter from there.
TARGET_PYTHON = "3.12"


def prose_header(lock_path: Path) -> str:
    """The committed explanation at the top of a lock, which uv would discard.

    Stops at the generated declaration block, so regenerating replaces that
    block rather than accumulating a copy of it on every run.
    """

    if not lock_path.is_file():
        raise ReleaseError(
            f"{lock_path} does not exist yet. Write its header comment first — every lock "
            "explains which job installs it and what breaks if it drifts."
        )
    header: list[str] = []
    for line in lock_path.read_text(encoding="utf-8").splitlines():
        if line.startswith(DECLARATION_SENTINEL):
            break
        if line.strip() and not line.startswith("#"):
            break
        header.append(line)
    while header and not header[-1].strip():
        header.pop()
    if not header:
        raise ReleaseError(f"{lock_path} has no header comment to preserve.")
    return "\n".join(header) + "\n"


def compile_command(target: LockTarget, *, uv: str = "uv") -> list[str]:
    command = [
        uv,
        "pip",
        "compile",
        "--universal",
        "--generate-hashes",
        "--no-header",
        "--python-version",
        TARGET_PYTHON,
    ]
    for extra in target.extras:
        command += ["--extra", extra]
    command.append(target.source)
    return command


def _pinned_uv_version(root: Path) -> str | None:
    lockfile = root / "constraints/release-publish.txt"
    if not lockfile.is_file():
        return None
    match = re.search(r"^uv==(\S+)", lockfile.read_text(encoding="utf-8"), re.MULTILINE)
    return match.group(1) if match else None


def update_lock(target: LockTarget, *, root: Path, uv: str) -> Path:
    lock_path = root / target.lock
    header = prose_header(lock_path)
    # Read the declarations before compiling, from the same source uv is about
    # to read, so the recorded block describes this resolution and not a
    # neighbouring edit.
    declarations = render_declarations(declared_requirements(target, root=root))
    result = subprocess.run(  # noqa: S603 - argument list is built here, never a shell string
        compile_command(target, uv=uv),
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise ReleaseError(f"uv pip compile failed for {target.source}:\n{result.stderr.strip()}")
    body = result.stdout.strip("\n")
    if not body:
        raise ReleaseError(f"uv pip compile produced nothing for {target.source}.")
    lock_path.write_text(f"{header}{declarations}{body}\n", encoding="utf-8")
    return lock_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the committed dependency locks.")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--uv", default="uv", help="path to the uv executable")
    parser.add_argument(
        "lock",
        nargs="*",
        help=(
            "lock paths to recompile; default all. Recompiling picks up whatever the "
            "index now offers, so a change to one lock's declarations should not drag "
            "the others forward with it."
        ),
    )
    args = parser.parse_args(argv)

    selected = LOCK_TARGETS
    if args.lock:
        requested = {Path(item).as_posix() for item in args.lock}
        selected = tuple(target for target in LOCK_TARGETS if target.lock in requested)
        unknown = requested - {target.lock for target in LOCK_TARGETS}
        if unknown:
            sys.stderr.write(
                f"Dependency lock error: no such lock target: {', '.join(sorted(unknown))}. "
                f"Known: {', '.join(target.lock for target in LOCK_TARGETS)}.\n"
            )
            return 1

    resolved = shutil.which(args.uv)
    if resolved is None:
        sys.stderr.write(
            f"Dependency lock error: {args.uv} is not on PATH. Install uv "
            "(https://docs.astral.sh/uv/) — the locks are compiled with it.\n"
        )
        return 1

    version = subprocess.run(  # noqa: S603 - resolved absolute path, no shell
        [resolved, "--version"], capture_output=True, text=True, check=False
    ).stdout.strip()
    pinned = _pinned_uv_version(args.root)
    if pinned and pinned not in version:
        sys.stderr.write(
            f"Warning: compiling with {version}, but the publication toolchain pins uv=={pinned}. "
            "Resolutions can differ between resolver versions; review the diff.\n"
        )

    try:
        for target in selected:
            path = update_lock(target, root=args.root, uv=resolved)
            sys.stdout.write(f"Recompiled {path.relative_to(args.root)} from {target.source}.\n")
    except (ReleaseError, OSError) as exc:
        sys.stderr.write(f"Dependency lock error: {exc}\n")
        return 1

    sys.stdout.write("Now run: python scripts/verify_dependency_lock.py\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
